services:


# -------------- Middlewares ---------------

    itmedia_command_bus.middleware_validation:
        class: Itmedia\CommandBusBundle\Middleware\ValidationMiddleware
        arguments: ["@validator"]


# --------- Handler Mapper ---------------

    itmedia_command_bus.container_handler_mapper:
        class: Itmedia\CommandBusBundle\Handler\ContainerCommandHandlerMapper
        arguments: ["@service_container",[]]

