services:


# -------------- Middlewares ---------------

    infrastructure_command_bus.middleware_validation:
        class: Itmedia\CommandBusBundle\Middleware\ValidationMiddleware
        arguments: ["@validator"]


# --------- Handler Mapper ---------------

    infrastructure_command_bus.handler_mapper:
        class: Itmedia\CommandBusBundle\Handler\HandlerMapper
        arguments: ["@service_container",[]]





